import { readFileSync, writeFileSync, mkdirSync, copyFileSync, readdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';

const SAFE = /^[A-Za-z0-9._-]+\.tflite$/;

export function generateRequireMap(filenames) {
  for (const f of filenames) {
    if (!SAFE.test(f)) throw new Error(`invalid model filename: ${f}`);
  }
  const entries = filenames
    .map(f => `  '${f}': require('../../../assets/models/${f}'),`)
    .join('\n');
  return (
    `// Generated by scripts/sync-models.mjs. Do not edit.\n` +
    `export const bundledModels: Record<string, number> = {\n${entries}\n};\n`
  );
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const root = fileURLToPath(new URL('../', import.meta.url));
  const src = join(root, 'models');
  const dest = join(root, 'app/assets/models');

  rmSync(dest, { recursive: true, force: true });
  mkdirSync(dest, { recursive: true });

  const manifest = JSON.parse(readFileSync(join(src, 'manifest.json'), 'utf8'));
  const files = manifest.models.map(m => m.file);
  const present = new Set(readdirSync(src).filter(f => f.endsWith('.tflite')));

  for (const f of files) {
    if (!present.has(f)) {
      console.warn(`[sync-models] manifest lists ${f} but it is not in models/ — skipping`);
      continue;
    }
    copyFileSync(join(src, f), join(dest, f));
  }

  const copied = files.filter(f => present.has(f));
  mkdirSync(join(root, 'app/src/core/ml'), { recursive: true });
  writeFileSync(join(root, 'app/src/core/ml/bundledModels.ts'), generateRequireMap(copied), 'utf8');

  // Metro will not resolve imports outside app/, so the manifest is copied in.
  writeFileSync(
    join(root, 'app/src/core/ml/manifest.json'),
    JSON.stringify(manifest, null, 2) + '\n',
    'utf8',
  );

  console.log(`[sync-models] bundled ${copied.length} model(s)`);
}
